// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqVTWy82Hmaf_L0gcZ3IRlhXd9Wfgc8gg',
    appId: '1:719491739988:web:fe114715f62840d0d7d8c1',
    messagingSenderId: '719491739988',
    projectId: 'reward-yourself-c883c',
    authDomain: 'reward-yourself-c883c.firebaseapp.com',
    storageBucket: 'reward-yourself-c883c.appspot.com',
    measurementId: 'G-GXMJW09C6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27UMAFJdmz8BH1VT3E95fv_WEyTxvLRY',
    appId: '1:719491739988:android:df1f070bb25bc438d7d8c1',
    messagingSenderId: '719491739988',
    projectId: 'reward-yourself-c883c',
    storageBucket: 'reward-yourself-c883c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ILrtQDbAdQG-OVQbu6bjCfh5HdcZh7g',
    appId: '1:719491739988:ios:c15069826928457bd7d8c1',
    messagingSenderId: '719491739988',
    projectId: 'reward-yourself-c883c',
    storageBucket: 'reward-yourself-c883c.appspot.com',
    iosClientId: '719491739988-megn74579t2qi34libn3bgnf7oashclv.apps.googleusercontent.com',
    iosBundleId: 'com.example.rewardYourself',
  );
}
